//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MonaWebApp.Models.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Project
    {
        public int ProjectId { get; set; }
        public int ProjectName { get; set; }
        public int ProjectModel { get; set; }
        public int ProjectMakeUp { get; set; }
        public int ProjectPhotographer { get; set; }
        public int ProjectPhoto { get; set; }
    
        public virtual Human Human { get; set; }
        public virtual Human Human1 { get; set; }
        public virtual Human Human2 { get; set; }
        public virtual Photo Photo { get; set; }
    }
}
